function addTableList(name,arr)
{
	$(name).find('.list-box').html('');
	console.log($(name));
	for(let i=0;i<arr.length;i++)
	{
		setTimeout(function(){
			$(name).find('.list-box').append('<div class="table-list"><p>'+arr[i].address+'</p><p>'+arr[i].name+'</p><p>'+arr[i].name1+'</p><p class="num">'+arr[i].num+'</p><p>'+arr[i].phone+'</p></div>')
		},200*i)

	}
}
$(function(){
	var coreArr=[
		{
			address:'安亭镇',
			leader:'马维康',
			name:'李金华',
			name1:'张明玉',
			num:'6',
			phone:'66742920',
		},
		{
			address:'嘉定新城(马陆镇)',
			leader:'马维康',
			name:'王鑫',
			name1:'张晨',
			num:'12',
			phone:'66742920',
		},
		{
			address:'南翔镇',
			leader:'马维康',
			name:'李嘉',
			name1:'何维',
			num:'6',
			phone:'66742920',
		},
		{
			address:'江桥镇',
			leader:'马维康',
			name:'王亮',
			name1:'刘颖',
			num:'12',
			phone:'66742920',
		},
		{
			address:'徐行镇',
			leader:'马维康',
			name:'冯青青',
			name1:'谢云峰',
			num:'6',
			phone:'66742920',
		},
		{
			address:'外冈镇',
			leader:'马维康',
			name:'王尔陆',
			name1:'胡新宇',
			num:'12',
			phone:'66742920',
		},
		{
			address:'华亭镇',
			leader:'马维康',
			name:'李思佳',
			name1:'张欣桐',
			num:'6',
			phone:'66742920',
		},
		{
			address:'嘉定镇街道',
			leader:'马维康',
			name:'刘梦瑶',
			name1:'寇小天',
			num:'12',
			phone:'66742920',
		},
		{
			address:'新成路街道',
			leader:'马维康',
			name:'李某某',
			name1:'张某',
			num:'6',
			phone:'66742920',
		},
		{
			address:'许行镇',
			leader:'马维康',
			name:'王某',
			name1:'张某',
			num:'12',
			phone:'66742920',
		},
		{
			address:'嘉定新城(马陆镇)',
			leader:'马维康',
			name:'李某某',
			name1:'张某',
			num:'6',
			phone:'66742920',
		},
		{
			address:'许行镇',
			leader:'马维康',
			name:'王某',
			name1:'张某',
			num:'12',
			phone:'66742920',
		},
	]
	addTableList1('.core-table',coreArr);
	var linkageArr=[
		{
			address:'嘉定新城(马陆镇)',
			leader:'马维康',
			name:'李某某',
			name1:'张某',
			num:'6',
			phone:'66742920',
		},
		{
			address:'许行镇',
			leader:'马维康',
			name:'王某',
			name1:'张某',
			num:'12',
			phone:'66742920',
		},				{
			address:'嘉定新城(马陆镇)',
			leader:'马维康',
			name:'李某某',
			name1:'张某',
			num:'6',
			phone:'66742920',
		},
		{
			address:'许行镇',
			leader:'马维康',
			name:'王某',
			name1:'张某',
			num:'12',
			phone:'66742920',
		},				{
			address:'嘉定新城(马陆镇)',
			leader:'马维康',
			name:'李某某',
			name1:'张某',
			num:'6',
			phone:'66742920',
		}
	]
	addTableList1('.linkage-table',linkageArr)

})

function addTableList1(name,arr)
{
	$(name).find('.list-box').html('');
	console.log($(name));
	for(let i=0;i<arr.length;i++)
	{
		setTimeout(function(){
			$(name).find('.list-box').append('<div class="table-list"><p>'+arr[i].address+'</p><p>'+arr[i].leader+'</p><p>'+arr[i].name+'</p><p>'+arr[i].name1+'</p><p class="num">'+arr[i].num+'</p><p>'+arr[i].phone+'</p></div>')
		},200*i)

	}
}
