function addTableList(name,arr)
{
	$(name).find('.list-box').html('');
	console.log($(name));
	for(let i=0;i<arr.length;i++)
	{
		setTimeout(function(){
			$(name).find('.list-box').append('<div class="table-list"><p>'+arr[i].address+'</p><p>'+arr[i].name+'</p><p>'+arr[i].name1+'</p><p class="num">'+arr[i].num+'</p><p>'+arr[i].phone+'</p></div>')
		},200*i)

	}
}
$(function(){
	var coreArr=[
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},
]
addTableList('.core-table',coreArr);
var linkageArr=[
	{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},				{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	},
	{
		address:'许行镇',
		name:'王某',
		name1:'张某',
		num:'12',
		phone:'66742920',
	},				{
		address:'嘉定新城(马陆镇)',
		name:'李某某',
		name1:'张某',
		num:'6',
		phone:'66742920',
	}
]
addTableList('.linkage-table',linkageArr)

})
